# Generated by Django 5.2.4 on 2025-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("m3u", "0018_add_profile_custom_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="m3uaccountprofile",
            name="is_backup_only",
            field=models.BooleanField(
                default=False,
                help_text="Only use this profile as failover when the primary profile URL fails DNS resolution. Backup profiles share the connection limit with the default profile.",
            ),
        ),
    ]
